### ISSUE TITLE
Crash on dart files withtout semicolons at the end

### ISSUE THREAD

**Issue by D00mch** [UserNobody14/tree-sitter-dart#28] opened 2022-05-26 07:55 UTC
Described in main treesitter repo [issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/2961) (treesitter should not crash anyway), but seems to deserved being mention here too.

### To Reproduce
- Create empty file;
- Run :set ft=dart;
- Write any symbol except semicolon.

**Comment by TimWhiting** [comment] 2023-05-05 06:24
Just installed tree sitter with neovim, not seeing this. Can anyone confirm?

**Comment by momrak** [comment] 2023-05-05 07:08
I had this for quite some time, but haven't seen it in while now, so might be the root cause has been fixed in some other update?

**Closed** 2023-05-05 16:22 UTC
